<?php

namespace Drupal\office_html\Plugin\Filter;

use Drupal\filter\FilterProcessResult;
use Drupal\filter\Plugin\FilterBase;
use Drupal\Core\StringTranslation\StringTranslationTrait;

/**
 * Configuration the filter.
 *
 * @Filter(
 *   id = "office_html_convert",
 *   title = @Translation("Convert HTML entities to standard text"),
 *   description = @Translation("Converts HTML entities generated by Office programs into standard text entities."),
 *   type = Drupal\filter\Plugin\FilterInterface::TYPE_TRANSFORM_REVERSIBLE,
 * )
 */
class OfficeHtmlConvert extends FilterBase {

  use StringTranslationTrait;

  /**
   * Process filter that convert the display of user input.
   */
  public function process($text, $langcode) {

    $find = array['&#039;', '&#0160;', '&nbsp;', '', '', '', '', '&rsquo;', '&lsquo;', '&ldquo;', '&rdquo;', '&mdash;', '&ndash;'];
    $replace = array["'", ' ', ' ', '"', '"', "'", "'", "'", "'", '"', '"', '--', '-'];
    $result = str_replace($find, $replace, $text);
    return new FilterProcessResult($result);
  }

  /**
   * Tips for when filtering.
   */
  public function tips($long = FALSE) {

    $this->t('HTML entities generated by Microsoft Office are converted to plain-text equivalents');

  }

}
