<?php

namespace Drupal\office_html\Plugin\Filter;

use Drupal\filter\FilterProcessResult;
use Drupal\filter\Plugin\FilterBase;
use Drupal\Core\StringTranslation\StringTranslationTrait;

/**
 * Configuration the filter.
 *
 * @Filter(
 *   id = "office_html_strip",
 *   title = @Translation("Strip style, script, and xml tags and content"),
 *   description = @Translation("Removes header tags (style, script, xml) and all included content, otherwise left behind by the core HTML filter."),
 *   type = Drupal\filter\Plugin\FilterInterface::TYPE_TRANSFORM_REVERSIBLE,
 * )
 */
class OfficeHtmlStrip extends FilterBase {

  use StringTranslationTrait;

  /**
   * Process stripping out malicious HTML.
   */
  public function process($text, $langcode) {

    $text = preg_replace('/<style.*?<\/style>/xmsi', '', $text);
    $text = preg_replace('/<xml.*?<\/xml>/xmsi', '', $text);
    $text = preg_replace('/<script.*?<\/script>/xmsi', '', $text);
    $text = preg_replace('/<w:WordDocument.*?<\/w:WordDocument>/xmsi', '', $text);
    return new FilterProcessResult($text);

  }

  /**
   * Tips for when filtering.
   */
  public function tips($long = FALSE) {

    $this->t('HTML header tags generated by Microsoft Office are stripped');

  }

}
